import { BLOCK_TYPES, DEFAULT_EMAIL_THEME } from './defaultBlocks.js';

export const PREBUILT_EMAIL_TEMPLATES = [
  {
    id: 'welcome-onboarding',
    nameAr: 'الترحيب والانضمام للمنصة',
    nameEn: 'Welcome & Onboarding',
    category: 'onboarding',
    badge: 'الأكثر استخداماً',
    thumbnail: '🚀',
    descriptionAr: 'قالب ترحيبي جذاب للمستخدمين الجدد مع زر توجيه لمركز التحكم',
    descriptionEn: 'Welcome new signups with onboarding tips and CTA',
    theme: { ...DEFAULT_EMAIL_THEME },
    blocks: [
      {
        id: 'w_hdr',
        type: BLOCK_TYPES.HEADER,
        logoText: 'UpKlick',
        logoUrl: 'https://upklick.net/best_logo_dark.png',
        tagline: 'منصة التسويق والأتمتة الذكية',
        align: 'center',
        logoWidth: 160,
        showTagline: false,
        paddingTop: 16,
        paddingBottom: 16,
        backgroundColor: 'transparent'
      },
      {
        id: 'w_hero',
        type: BLOCK_TYPES.IMAGE,
        imageUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&auto=format&fit=crop&q=80',
        altText: 'Welcome to UpKlick',
        linkUrl: 'https://upklick.net/dashboard',
        borderRadius: 14,
        width: 100,
        align: 'center',
        paddingTop: 8,
        paddingBottom: 16
      },
      {
        id: 'w_title',
        type: BLOCK_TYPES.HEADING,
        text: 'أهلاً بك في UpKlick، رحلتك للنمو تبدأ هنا! 👋',
        level: 'h1',
        color: '#ffffff',
        align: 'right',
        fontSize: 24,
        fontWeight: 'bold',
        paddingTop: 8,
        paddingBottom: 8
      },
      {
        id: 'w_text',
        type: BLOCK_TYPES.TEXT,
        content: 'مرحباً {{name}}،\n\nنحن سعداء للغاية بانضمامك إلى مجتمع UpKlick! حسابك جاهز الآن بالكامل لاستكشاف أدوات التسويق، الـ CRM الذكي، الفانلز، وأتمتة العمليات لزيادة مبيعاتك وتوفير وقتك الثمين.',
        color: '#cbd5e1',
        align: 'right',
        fontSize: 15,
        lineHeight: 1.7,
        paddingTop: 8,
        paddingBottom: 12
      },
      {
        id: 'w_card',
        type: BLOCK_TYPES.CARD,
        icon: '💡',
        title: 'خطواتك الأولى لتحقيق أقصى استفادة:',
        description: '1. أكمل إعداد ملف شركتك وعلامتك التجارية\n2. أنشئ أول قمع مبيعات أو صفحة هبوط\n3. فعّل حملات التواصل التلقائي مع عملائك',
        backgroundColor: 'rgba(255, 107, 53, 0.08)',
        borderColor: 'rgba(255, 107, 53, 0.3)',
        titleColor: '#FF6B35',
        textColor: '#e2e8f0',
        align: 'right',
        borderRadius: 12,
        padding: 16,
        paddingTop: 12,
        paddingBottom: 14
      },
      {
        id: 'w_btn',
        type: BLOCK_TYPES.BUTTON,
        text: 'الدخول إلى لوحة التحكم الآن ←',
        url: 'https://upklick.net/dashboard',
        style: 'gradient',
        backgroundColor: '#FF6B35',
        gradientStart: '#FF6B35',
        gradientEnd: '#6C35FF',
        textColor: '#ffffff',
        borderRadius: 12,
        width: 'auto',
        align: 'center',
        paddingX: 36,
        paddingY: 15,
        fontSize: 15,
        fontWeight: 'bold',
        paddingTop: 16,
        paddingBottom: 16
      },
      {
        id: 'w_div',
        type: BLOCK_TYPES.DIVIDER,
        style: 'solid',
        color: 'rgba(255, 255, 255, 0.08)',
        thickness: 1,
        width: 100,
        paddingTop: 16,
        paddingBottom: 16
      },
      {
        id: 'w_social',
        type: BLOCK_TYPES.SOCIAL,
        platforms: [
          { name: 'Telegram', url: 'https://t.me/upklick', icon: '✈️' },
          { name: 'Twitter', url: 'https://twitter.com/upklick', icon: '𝕏' },
          { name: 'Instagram', url: 'https://instagram.com/upklick', icon: '📷' }
        ],
        align: 'center',
        iconStyle: 'circle',
        paddingTop: 8,
        paddingBottom: 8
      },
      {
        id: 'w_ftr',
        type: BLOCK_TYPES.FOOTER,
        companyName: 'UpKlick Inc.',
        address: 'منصة إدارة وتوسيع الأعمال الرقمية',
        unsubscribeText: 'لا ترغب في تلقي رسائل الترحيب والتحديثات؟',
        unsubscribeLabel: 'إلغاء الاشتراك من هنا',
        textColor: '#64748b',
        linkColor: '#94a3b8',
        align: 'center',
        paddingTop: 16,
        paddingBottom: 24
      }
    ]
  },
  {
    id: 'trial-ending-upgrade',
    nameAr: 'تذكير انتهاء التجربة المجانية والترقية',
    nameEn: 'Trial Expiration & Upgrade',
    category: 'conversion',
    badge: 'تحويل عالي',
    thumbnail: '⏳',
    descriptionAr: 'رسالة إلحاح عالية التحويل لتشجيع المشترك على الترقية قبل توقف الحساب',
    descriptionEn: 'High conversion urgency email for expiring trial users',
    theme: { ...DEFAULT_EMAIL_THEME },
    blocks: [
      {
        id: 't_hdr',
        type: BLOCK_TYPES.HEADER,
        logoText: 'UpKlick',
        logoUrl: 'https://upklick.net/best_logo_dark.png',
        tagline: 'UpKlick',
        align: 'center',
        logoWidth: 150,
        paddingTop: 16,
        paddingBottom: 14
      },
      {
        id: 't_card',
        type: BLOCK_TYPES.CARD,
        icon: '⚠️',
        title: 'تنبيه: تنتهي تجربتك المجانية قريباً!',
        description: 'تبقى القليل من الوقت على انتهاء فترة التجربة. لا تفقد الوصول إلى بياناتك، قنوات البيع، ورصيد الذكاء الاصطناعي.',
        backgroundColor: 'rgba(239, 68, 68, 0.1)',
        borderColor: 'rgba(239, 68, 68, 0.35)',
        titleColor: '#f87171',
        textColor: '#f1f5f9',
        align: 'right',
        borderRadius: 14,
        padding: 16,
        paddingTop: 10,
        paddingBottom: 12
      },
      {
        id: 't_title',
        type: BLOCK_TYPES.HEADING,
        text: 'حافظ على استمرارية نمو مشروعك مع باقات UpKlick ✨',
        level: 'h2',
        color: '#ffffff',
        align: 'right',
        fontSize: 22,
        fontWeight: 'bold',
        paddingTop: 10,
        paddingBottom: 6
      },
      {
        id: 't_text',
        type: BLOCK_TYPES.TEXT,
        content: 'عزيزنا {{name}}،\n\nلقد قمت بخطوات رائعة خلال فترة التجربة! للترقية والاستمرار دون أي انقطاع في خدماتك وأتمتة مبيعاتك، اختر الباقة المناسبة لاحتياجاتك الآن مع خصم إضافي.',
        color: '#cbd5e1',
        align: 'right',
        fontSize: 15,
        lineHeight: 1.7,
        paddingTop: 6,
        paddingBottom: 10
      },
      {
        id: 't_coupon',
        type: BLOCK_TYPES.COUPON,
        code: 'PROUPGRADE30',
        discount: 'خصم 30% على أول 3 أشهر عند الترقية اليوم',
        expiresText: '⏳ الكوبون صالح لمدة 24 ساعة فقط للمشتركين التجريبيين',
        backgroundColor: 'rgba(108, 53, 255, 0.12)',
        borderColor: '#6C35FF',
        codeColor: '#FF6B35',
        paddingTop: 12,
        paddingBottom: 14
      },
      {
        id: 't_btn',
        type: BLOCK_TYPES.BUTTON,
        text: 'ترقية حسابي وتفعيل الخصم ←',
        url: 'https://upklick.net/pricing',
        style: 'gradient',
        backgroundColor: '#FF6B35',
        gradientStart: '#FF6B35',
        gradientEnd: '#6C35FF',
        textColor: '#ffffff',
        borderRadius: 12,
        width: 'auto',
        align: 'center',
        paddingX: 34,
        paddingY: 15,
        fontSize: 15,
        fontWeight: 'bold',
        paddingTop: 16,
        paddingBottom: 16
      },
      {
        id: 't_ftr',
        type: BLOCK_TYPES.FOOTER,
        companyName: 'UpKlick Inc.',
        address: 'فريق نجاح العملاء — نحن هنا لدعمك دائماً',
        unsubscribeText: 'لا ترغب في تلقي رسائل الترقية؟',
        unsubscribeLabel: 'إلغاء الاشتراك',
        textColor: '#64748b',
        linkColor: '#94a3b8',
        align: 'center',
        paddingTop: 16,
        paddingBottom: 24
      }
    ]
  },
  {
    id: 'promo-flash-sale',
    nameAr: 'عرض ترويجي وتخفيض حصري',
    nameEn: 'Flash Sale & Promo Discount',
    category: 'promotion',
    badge: 'مبيعات فورية',
    thumbnail: '🔥',
    descriptionAr: 'قالب تسويقي ناري مع كوبون خصم وزر شراء جذاب',
    descriptionEn: 'High impact flash sale email with discount badge and CTA',
    theme: { ...DEFAULT_EMAIL_THEME },
    blocks: [
      {
        id: 'p_hdr',
        type: BLOCK_TYPES.HEADER,
        logoText: 'UpKlick',
        logoUrl: 'https://upklick.net/best_logo_dark.png',
        align: 'center',
        logoWidth: 160,
        paddingTop: 16,
        paddingBottom: 14
      },
      {
        id: 'p_hero',
        type: BLOCK_TYPES.IMAGE,
        imageUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&auto=format&fit=crop&q=80',
        altText: 'Mega Flash Sale',
        linkUrl: 'https://upklick.net/pricing',
        borderRadius: 14,
        width: 100,
        align: 'center',
        paddingTop: 6,
        paddingBottom: 14
      },
      {
        id: 'p_title',
        type: BLOCK_TYPES.HEADING,
        text: '🔥 عرض خاص ومحدود: وفّر حتى 50% على جميع الخطط السنوية!',
        level: 'h1',
        color: '#ffffff',
        align: 'right',
        fontSize: 24,
        fontWeight: 'bold',
        paddingTop: 8,
        paddingBottom: 8
      },
      {
        id: 'p_text',
        type: BLOCK_TYPES.TEXT,
        content: 'مرحباً {{name}}،\n\nلفترة محدودة جداً، نمنحك فرصة الاستفادة من أقوى عروض الموسم لتجهيز مشروعك بأحدث أدوات الأتمتة والذكاء الاصطناعي وبنصف السعر المعتاد.',
        color: '#cbd5e1',
        align: 'right',
        fontSize: 15,
        lineHeight: 1.7,
        paddingTop: 6,
        paddingBottom: 10
      },
      {
        id: 'p_cols',
        type: BLOCK_TYPES.COLUMNS,
        col1: {
          icon: '🎁',
          title: 'رصيد كريدت إضافي',
          description: 'مضاعفة رصيد الذكاء الاصطناعي مجاناً مع أي باقة سنوية.'
        },
        col2: {
          icon: '⚡',
          title: 'دعم VIP فوري',
          description: 'مدير حساب مخصص لمساعدتك في بناء استراتيجيتك.'
        },
        cardBackground: 'rgba(255, 255, 255, 0.03)',
        borderColor: 'rgba(255, 255, 255, 0.08)',
        titleColor: '#ffffff',
        textColor: '#94a3b8',
        paddingTop: 10,
        paddingBottom: 12
      },
      {
        id: 'p_coupon',
        type: BLOCK_TYPES.COUPON,
        code: 'VIP50OFF',
        discount: 'خصم 50% + شهرين مجاناً',
        expiresText: '⚠️ ينتهي العرض عند اكتمال أول 100 مشترك',
        backgroundColor: 'rgba(255, 107, 53, 0.1)',
        borderColor: '#FF6B35',
        codeColor: '#FF6B35',
        paddingTop: 12,
        paddingBottom: 14
      },
      {
        id: 'p_btn',
        type: BLOCK_TYPES.BUTTON,
        text: 'اغتنم العرض الحصري الآن 🚀',
        url: 'https://upklick.net/pricing',
        style: 'gradient',
        backgroundColor: '#FF6B35',
        gradientStart: '#FF6B35',
        gradientEnd: '#6C35FF',
        textColor: '#ffffff',
        borderRadius: 12,
        width: 'auto',
        align: 'center',
        paddingX: 38,
        paddingY: 16,
        fontSize: 16,
        fontWeight: 'bold',
        paddingTop: 16,
        paddingBottom: 16
      },
      {
        id: 'p_ftr',
        type: BLOCK_TYPES.FOOTER,
        companyName: 'UpKlick Inc.',
        address: 'تطبق الشروط والأحكام الخاصة بالعروض الموسمية',
        unsubscribeText: 'لا ترغب في تلقي العروض الترويجية؟',
        unsubscribeLabel: 'إلغاء الاشتراك من هنا',
        textColor: '#64748b',
        linkColor: '#94a3b8',
        align: 'center',
        paddingTop: 16,
        paddingBottom: 24
      }
    ]
  },
  {
    id: 'feature-product-update',
    nameAr: 'إعلان ميزات وتحديثات جديدة',
    nameEn: 'Product & Feature Update',
    category: 'updates',
    badge: 'تحديثات النظام',
    thumbnail: '✨',
    descriptionAr: 'إعلام المستخدمين بأحدث التحسينات والميزات المضافة للنظام',
    descriptionEn: 'Announce new tools and system improvements',
    theme: { ...DEFAULT_EMAIL_THEME },
    blocks: [
      {
        id: 'f_hdr',
        type: BLOCK_TYPES.HEADER,
        logoText: 'UpKlick',
        logoUrl: 'https://upklick.net/best_logo_dark.png',
        align: 'center',
        logoWidth: 160,
        paddingTop: 16,
        paddingBottom: 14
      },
      {
        id: 'f_title',
        type: BLOCK_TYPES.HEADING,
        text: '✨ تحديثات شهرية كبرى: إليك ما أضفناه لتسريع أعمالك!',
        level: 'h1',
        color: '#ffffff',
        align: 'right',
        fontSize: 23,
        fontWeight: 'bold',
        paddingTop: 8,
        paddingBottom: 8
      },
      {
        id: 'f_text',
        type: BLOCK_TYPES.TEXT,
        content: 'مرحباً {{name}}،\n\nنواصل العمل باستمرار لتقديم أفضل تجربة لإدارة مشاريعك. إليك أبرز الميزات والأدوات الجديدة التي تم إطلاقها هذا الأسبوع:',
        color: '#cbd5e1',
        align: 'right',
        fontSize: 15,
        lineHeight: 1.7,
        paddingTop: 6,
        paddingBottom: 10
      },
      {
        id: 'f_card1',
        type: BLOCK_TYPES.CARD,
        icon: '🎨',
        title: '1. مصمم الإيميلات المرئي الجديد (Drag & Drop)',
        description: 'صمم حملات بريدية فائقة الجمال بضغطة زر مع قوالب جاهزة ومعاينة حية للموبايل.',
        backgroundColor: 'rgba(108, 53, 255, 0.08)',
        borderColor: 'rgba(108, 53, 255, 0.25)',
        titleColor: '#a78bfa',
        textColor: '#e2e8f0',
        align: 'right',
        borderRadius: 12,
        padding: 16,
        paddingTop: 8,
        paddingBottom: 10
      },
      {
        id: 'f_card2',
        type: BLOCK_TYPES.CARD,
        icon: '📊',
        title: '2. تحليلات دقيقة وسجلات إرسال متقدمة',
        description: 'تتبع معدلات الفتح والتسليم والنقر لكل رسالة مع سجلات فورية لأي أخطاء من المزود.',
        backgroundColor: 'rgba(16, 185, 129, 0.08)',
        borderColor: 'rgba(16, 185, 129, 0.25)',
        titleColor: '#34d399',
        textColor: '#e2e8f0',
        align: 'right',
        borderRadius: 12,
        padding: 16,
        paddingTop: 8,
        paddingBottom: 10
      },
      {
        id: 'f_btn',
        type: BLOCK_TYPES.BUTTON,
        text: 'تجربة الميزات الجديدة الآن ←',
        url: 'https://upklick.net/dashboard',
        style: 'gradient',
        backgroundColor: '#FF6B35',
        gradientStart: '#FF6B35',
        gradientEnd: '#6C35FF',
        textColor: '#ffffff',
        borderRadius: 12,
        width: 'auto',
        align: 'center',
        paddingX: 32,
        paddingY: 14,
        fontSize: 15,
        fontWeight: 'bold',
        paddingTop: 16,
        paddingBottom: 16
      },
      {
        id: 'f_ftr',
        type: BLOCK_TYPES.FOOTER,
        companyName: 'UpKlick Inc.',
        address: 'نشرة التحديثات الدورية — UpKlick Changelog',
        unsubscribeText: 'لا ترغب في تلقي تحديثات المنتجات؟',
        unsubscribeLabel: 'إلغاء الاشتراك',
        textColor: '#64748b',
        linkColor: '#94a3b8',
        align: 'center',
        paddingTop: 16,
        paddingBottom: 24
      }
    ]
  },
  {
    id: 'webinar-invite',
    nameAr: 'دعوة ويبينار وماستركلاس مباشر',
    nameEn: 'Live Webinar Invitation',
    category: 'events',
    badge: 'تفاعل عالي',
    thumbnail: '🎙️',
    descriptionAr: 'دعوة لحضور تدريب أو ويبينار مباشر مع زر حجز مقعد',
    descriptionEn: 'Invite subscribers to live training or webinar masterclass',
    theme: { ...DEFAULT_EMAIL_THEME },
    blocks: [
      {
        id: 'wb_hdr',
        type: BLOCK_TYPES.HEADER,
        logoText: 'UpKlick',
        logoUrl: 'https://upklick.net/best_logo_dark.png',
        align: 'center',
        logoWidth: 160,
        paddingTop: 16,
        paddingBottom: 14
      },
      {
        id: 'wb_title',
        type: BLOCK_TYPES.HEADING,
        text: '🎙️ ويبينار مباشر: كيف تبني نظام مبيعات أوتوماتيكي متكامل؟',
        level: 'h1',
        color: '#ffffff',
        align: 'right',
        fontSize: 23,
        fontWeight: 'bold',
        paddingTop: 8,
        paddingBottom: 8
      },
      {
        id: 'wb_card',
        type: BLOCK_TYPES.CARD,
        icon: '📅',
        title: 'موعد الويبينار: الخميس القادم الساعة 8:00 مساءً بتوقيت مكة',
        description: 'بث مباشر تفاعلي + جلسة أسئلة وأجوبة مفتوحة + حقيبة أدوات وقوالب تسويقية مجاناً للحاضرين.',
        backgroundColor: 'rgba(255, 107, 53, 0.08)',
        borderColor: 'rgba(255, 107, 53, 0.3)',
        titleColor: '#FF6B35',
        textColor: '#e2e8f0',
        align: 'right',
        borderRadius: 12,
        padding: 16,
        paddingTop: 10,
        paddingBottom: 12
      },
      {
        id: 'wb_text',
        type: BLOCK_TYPES.TEXT,
        content: 'مرحباً {{name}}،\n\nندعوك لحضور جلسة استراتيجية مكثفة نكشف فيها خطوة بخطوة كيف تستخدم قمع المبيعات والتسويق الذكي لتحويل الزوار العاديين إلى عملاء دائمين في مشروعك.',
        color: '#cbd5e1',
        align: 'right',
        fontSize: 15,
        lineHeight: 1.7,
        paddingTop: 6,
        paddingBottom: 10
      },
      {
        id: 'wb_btn',
        type: BLOCK_TYPES.BUTTON,
        text: 'احجز مقعدك المجاني في الويبينار 🎟️',
        url: 'https://upklick.net',
        style: 'gradient',
        backgroundColor: '#FF6B35',
        gradientStart: '#FF6B35',
        gradientEnd: '#6C35FF',
        textColor: '#ffffff',
        borderRadius: 12,
        width: 'auto',
        align: 'center',
        paddingX: 36,
        paddingY: 16,
        fontSize: 15,
        fontWeight: 'bold',
        paddingTop: 16,
        paddingBottom: 16
      },
      {
        id: 'wb_ftr',
        type: BLOCK_TYPES.FOOTER,
        companyName: 'UpKlick Inc.',
        address: 'أكاديمية وفعاليات UpKlick التعليمية',
        unsubscribeText: 'لا ترغب في تلقي دعوات الويبينارات؟',
        unsubscribeLabel: 'إلغاء الاشتراك',
        textColor: '#64748b',
        linkColor: '#94a3b8',
        align: 'center',
        paddingTop: 16,
        paddingBottom: 24
      }
    ]
  }
];
